name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install SSH
      run: sudo apt-get install -y openssh-server
    - name: Start SSH Service
      run: sudo service ssh start
    - name: Set Password for runner user
      run: echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok tcp 22
