name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest  # Menggunakan Ubuntu sebagai base image

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract ngrok
      run: unzip ngrok.zip
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y openssh-server wget unzip
    - name: Auth ngrok
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable SSH
      run: sudo systemctl enable ssh && sudo systemctl start ssh
    - name: Set user password
      run: echo 'user:root' | sudo chpasswd
    - name: Create tunnel
      run: ./ngrok/ngrok tcp 22  # Mengarahkan port 22 (SSH) melalui ngrok
