name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip -d ngrok
        chmod +x ngrok/ngrok
    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: sudo sysctl -w net.ipv4.tcp_keepalive_time=1800
    - name: Enable RDP
      run: sudo ufw allow 3389/tcp
    - name: Set User Authentication
      run: sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config && sudo service ssh restart
    - name: Set Local User Password
      run: echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 3389
