name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389

    - name: Add user
      run: |
        sudo useradd -m user
        echo 'user:root' | sudo chpasswd
        sudo adduser user sudo

    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create Tunnel
      run: ./ngrok tcp 3389
